### ISSUE TITLE
localization

### ISSUE THREAD

**Issue by ogomez92** [Aurelius7309/BlackHole#3]
Hello,
I'm interested in localizing Black Hole into Spanish. I have a few questions:

1. Is this possible? Would we need to localize all the items, etc or does the game provide multi language support already which your scripts can hook into?
2. How prepared are your strings for localization?

Thanks!

**Comment by Aurelius7309** [comment]
Balatro already provides a localization system, and Black Hole uses the text available in-game wherever possible. There's some custom ones I've added, all you would have to do is translate those into Spanish. If it's unclear to you what an entry is doing, it might be helpful to search Black Hope's source code for the corresponding key, but feel free to ask me to clarify.

This is the English file you should use for reference: https://github.com/Aurelius7309/BlackHole/blob/main/localization%2Fen-us.lua

**Comment by ogomez92** [comment]
Hello,
I've seen an issue in Spanish, where it doesn't read the tags when they are
shown after skip for. Let me know if you need an example and I will put my
game back into Spanish to show you, but it's pretty straightforward, when
you are seeing the list of blinds and when you go down to skip blind it
won't read what the tag does.

Also, I will fork your project and translate it and make a new pr with the
Spanish file, is that ok?

**Comment by Aurelius7309** [comment]
Yeah that's perfect, thanks! I'm already investigating the issue with Blind tags and will push an update as soon as I'm able to resolve it.

**Comment by ogomez92** [comment]
Hey has there been any progress on this? Let me know if you need help. I've tried to make sense at the UI definitions file thinking the dreaded issue might stem from there, but I don't really know how to work that file, it's not very readable.. Can you explain it a bit?

Thanks.

**Comment by Aurelius7309** [comment]
From what I can tell, #9 does address that sort of issue. I went ahead and merged it. Let me know if the issue persists though

**Comment by ogomez92** [comment]
Thank you, much appreciated. It's fixed now.
